services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - HTTP_PROXY=${HTTP_PROXY:-http://127.0.0.1:6152}
        - HTTPS_PROXY=${HTTPS_PROXY:-http://127.0.0.1:6152}
        - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1,.local}
    image: samsoncj/presenton:development-proxy
    ports:
      - "5002:80"
    volumes:
      - .:/app
      - ./app_data:/app_data
    environment:
      - CAN_CHANGE_KEYS=${CAN_CHANGE_KEYS}
      - LLM=${LLM}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_MODEL=${GOOGLE_MODEL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - CUSTOM_LLM_URL=${CUSTOM_LLM_URL}
      - CUSTOM_LLM_API_KEY=${CUSTOM_LLM_API_KEY}
      - CUSTOM_MODEL=${CUSTOM_MODEL}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - EXTENDED_REASONING=${EXTENDED_REASONING}
      - TOOL_CALLS=${TOOL_CALLS}
      - DISABLE_THINKING=${DISABLE_THINKING}
      - WEB_GROUNDING=${WEB_GROUNDING}
      - DATABASE_URL=${DATABASE_URL}
      - DISABLE_ANONYMOUS_TRACKING=${DISABLE_ANONYMOUS_TRACKING}
      # Proxy settings for runtime
      - HTTP_PROXY=${HTTP_PROXY:-http://127.0.0.1:6152}
      - HTTPS_PROXY=${HTTPS_PROXY:-http://127.0.0.1:6152}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1,.local}