version: '3.8'

services:
  frpc:
    image: snowdreamtech/frpc:latest
    container_name: frpc
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    env_file:
      - .env